#!/bin/bash

java_version="19"

if [ -n "$1" ]; then
    java_version=$1
fi

clear

echo "Starting the server configuration..."

sudo apt-get update > /dev/null
echo -e "\e[32mupdated packages\e[0m"

sudo apt-get install openjdk-$java_version-jre > /dev/null
echo -e "\e[32minstalled java version \e[32;1m$java_version\e[0m"

mkdir minecraft
cd minecraft

wget https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/20/downloads/paper-1.20.1-20.jar > /dev/null
echo -e "\e[32mdownloaded the server file\e[0m"

mv *.jar server.jar > /dev/null
echo -e "\e[32mrenamed the server file to server.jar\e[0m"

cd ..

if [ ! -f "plugins.conf" ]; then
    touch "plugins.conf"
    echo -e "\e[32mcreated the plugins.conf file\e[0m"
fi

if [ -s "plugins.conf" ]; then
    mapfile -t plugins < plugins.conf
    cd minecraft
    mkdir plugins
    cd plugins
    
    touch readme.md
    echo "The files are indexed in the order that they where put in the **plugins.conf** file." > readme.md
    
    echo "downloading plugins..."
    for index in "${!plugins[@]}"; do
        wget "${plugins[$index]}"
        mv "download" "plugin$index.jar"
    done
    echo -e "\e[32mdownloaded plugins\e[0m"
    cd ..
else
    cd minecraft
    echo -e "\e[31mthe \e[31;1mplugins.conf\e[0m\e[31m file is empty\e[0m"
fi

touch eula.txt
echo "eula=true" > eula.txt
echo -e "\e[32maccepted the eula agreements\e[0m"

echo "installing server files..."
java -Xmx2048M -Xms1024M -jar server.jar nogui > /dev/null &

# Save the PID of the Java process
java_pid=$!

# Wait until the server starts
until lsof -i :25565 | grep LISTEN > /dev/null; do
    sleep 1
done

sleep 30

kill $java_pid

sleep 30
echo -e "\e[32minstallation completed.\e[0m"

sed -i 's/difficulty=easy/difficulty=hard/' server.properties
sed -i 's/motd=A Minecraft Server/motd=Lubie majonez/' server.properties

wget "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fih1.redbubble.net%2Fimage.441548384.5893%2Fflat%2C750x%2C075%2Cf-pad%2C750x1000%2Cf8f8f8.jpg&f=1&nofb=1&ipt=6b4929b49f87b2c93170296084dc1640ff0bf0f018c4279f11e3413248594c29&ipo=images" --output-document=server-icon.png > /dev/null

convert server-icon.png -resize 64x64\! server-icon.png

#https://www.curseforge.com/api/v1/mods/31043/files/4586220/download
